#!/bin/bash

array=()

get_file_lines() 
{
    i=0
    while read line # Read a line
    do
        array[i]=$line # Put it into the array
        i=$(($i + 1))
    done < $1
}

get_file_lines "sync_ignore.txt"

exclusion_args=""
for i in "${array[@]}"
do
	exclusion_args=" $exclusion_args--exclude='$i' "
done

rsync -avz $exclusion_args ../ root@192.241.216.182:/var/www/async_test
