#!/bin/bash

#read list name from commandline argument

# options=':q:nd:h'
# if ! getopts $options cmd_args 
# then
# 	echo "list name expected."
# 	exit 1
# fi
if [ $# -lt 2 ] 
then
	echo "list name and mailman directory expected"
	exit 1
fi

if [ $# -gt 1 ] 
then
	echo "Too many arguments"
	exit 1
fi

MAILMAN_DIR=$2
ARCHIVE_DIR="./mailman/deleted_lists" #The directory to save the .tar.gz files containing .pck and the archives of deleted lists
TAR_DIR=$1"_files" 

mkdir -p $ARCHIVE_DIR

pck_dir=$MAILMAN_DIR"/lists/"$1
#public_archive_sym_link=$MAILMAN_DIR"/archives/public/"$1
private_archive_dir="$MAILMAN_DIR"/archives/private/"$1"
private_mbox_dir="$MAILMAN_DIR"/archives/private/"$1".mbox

echo $pck_dir
echo $public_archive_sym_link
echo $private_archive_dir
echo $private_mbox_dir

if [ ! -d $pck_dir ] || \
   #[ ! -f $public_archive_sym_link ] || \
   [ ! -d $private_archive_dir ] || \
   [ ! -d $private_mbox_dir ]
then
	echo "List directories missing."
	exit 1
fi

#create a temporary directory to copy the files that need to be archived into
mkdir -p $TAR_DIR
mkdir -p $TAR_DIR"/pck/"
mkdir -p $TAR_DIR"/archive/"
mkdir -p $TAR_DIR"/mbox/"

cp "$pck_dir"/* $TAR_DIR"/pck/"
cp -r "$private_archive_dir" "$TAR_DIR"/archive
cp -r "$private_mbox_dir" "$TAR_DIR"/mbox

"$MAILMAN_DIR"/bin/rmlist -a "$1"

#tar-ball creation:
echo "creating tar archive..."
tar -cvzf "$ARCHIVE_DIR"/"$TAR_DIR".tgz "$TAR_DIR"

rm -rf "$TAR_DIR"

